==12648== Memcheck, a memory error detector
==12648== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==12648== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==12648== Command: python2 testconvexhull_one.py
==12648== Parent PID: 5796
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBFA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0x5e02020 is 2,624 bytes inside a block of size 2,731 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==  Address 0x5e5a020 is 256 bytes inside a block of size 2,711 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x5e48020 is 96 bytes inside a block of size 1,008 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0x5df6020 is 10,224 bytes inside a block of size 11,374 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==  Address 0x5df9020 is 1,168 bytes inside a block of size 1,384 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3038: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B344E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFDA8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==  Address 0x5f5a020 is 4,448 bytes inside a block of size 4,784 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3038: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4B8D51: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12648==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0x5fb4020 is 592 bytes inside a block of size 676 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B94F1: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12648==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B9120: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12648==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4F7EB7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E281C: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x6012020 is 0 bytes inside a block of size 768 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBED6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x421334: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC138: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC15B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC0F5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC4AF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBEB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0x6d3e020 is 416 bytes inside a block of size 552 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12648==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12648==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12648==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x6d3f020 is 16 bytes inside a block of size 32 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12648==    by 0x4D7A0E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC9B5: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4DD98C: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x6dcd020 is 64 bytes inside a block of size 544 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12648==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x418668: _PyObject_GC_Malloc (in /usr/bin/python2.7)
==12648==    by 0x4BA6A2: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Conditional jump or move depends on uninitialised value(s)
==12648==    at 0x4212E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12648==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Use of uninitialised value of size 8
==12648==    at 0x4212F3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12648==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12648==    by 0x4BAE2E: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x6dae020 is 16 bytes before a block of size 32 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C1731: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4DD98C: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x514123: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==  Address 0x6edf020 is 16 bytes inside a block of size 1,559 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x5139DF: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12648==    by 0x512D2F: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x5130BA: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==  Address 0x6edf020 is 16 bytes inside a block of size 1,559 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x5139DF: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12648==    by 0x512D2F: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4E16A7: ??? (in /usr/bin/python2.7)
==12648==    by 0x519089: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==  Address 0x6eed020 is 35,488 bytes inside a block of size 36,032 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B7072: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B4FFC: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4F7E29: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF4E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x6ef5020 is 48 bytes inside a block of size 88 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4F5CF7: PyCode_Optimize (in /usr/bin/python2.7)
==12648==    by 0x4F3D53: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFBEC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF34: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4F580C: PyCode_Optimize (in /usr/bin/python2.7)
==12648==    by 0x4F3D53: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFBEC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF34: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4F7E02: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AFE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0x6ef6020 is 32 bytes inside a block of size 1,536 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4ECBCE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F87A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFC1A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4BA22B: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==  Address 0x6ee0020 is 512 bytes inside a block of size 2,095 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x5130BA: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x514123: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x5139DF: ??? (in /usr/bin/python2.7)
==12648==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==  Address 0x6efa020 is 16 bytes after a block of size 64 in arena "client"
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4ECBCE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x6f11020 is 16 bytes before a block of size 1,536 alloc'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F87A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFC1A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F87BD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFC1A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x6f28020 is 224 bytes inside a block of size 768 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E776B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12648==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E6E5B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12648==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EF828: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x6f2a020 is 16 bytes after a block of size 32 in arena "client"
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F87A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFC1A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x6f42020 is 320 bytes inside a block of size 768 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7781: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12648==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E6E37: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12648==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Conditional jump or move depends on uninitialised value(s)
==12648==    at 0x4B5B72: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Use of uninitialised value of size 8
==12648==    at 0x4B5B8A: ??? (in /usr/bin/python2.7)
==12648==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EC083: ??? (in /usr/bin/python2.7)
==12648==    by 0x4ECB80: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x6f7b020 is 16 bytes before a block of size 768 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4F7E29: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF4E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x421334: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F2E5D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFCBC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EFB06: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBF4E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12648==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12648==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12648==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x507C2F: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x76f4020 is 352 bytes inside a block of size 1,104 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x557898: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x516811: ??? (in /usr/bin/python2.7)
==12648==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12648==    by 0x557657: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4B287B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C13C7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0x789d020 is 368 bytes inside a block of size 1,104 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x516811: ??? (in /usr/bin/python2.7)
==12648==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12648==    by 0x557657: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C2E68: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0x789e020 is 960 bytes inside a block of size 1,284 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B287B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C13C7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12648==    by 0x4DAA16: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x78f7020 is 6,448 bytes inside a block of size 7,309 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4D20C7: PyMember_SetOne (in /usr/bin/python2.7)
==12648==    by 0x42C38B: ??? (in /usr/bin/python2.7)
==12648==    by 0x42C09D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BCE86: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x9561020 is 384 bytes inside a block of size 1,104 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x557898: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x516811: ??? (in /usr/bin/python2.7)
==12648==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12648==    by 0x557657: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C9305: PyUnicodeUCS4_DecodeUTF8Stateful (in /usr/bin/python2.7)
==12648==    by 0x4B3726: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==  Address 0xa3e0020 is 32 bytes inside a block of size 128 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32D9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B349E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32D9: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==  Address 0xa414020 is 656 bytes inside a block of size 1,104 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x51718D: ??? (in /usr/bin/python2.7)
==12648==    by 0x577F29: ??? (in /usr/bin/python2.7)
==12648==    by 0x57738E: ??? (in /usr/bin/python2.7)
==12648==    by 0x557CCA: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545DEC: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==  Address 0xa415020 is 1,104 bytes inside a block of size 1,604 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B287B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C13C7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0xa415020 is 1,104 bytes inside a block of size 1,604 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12648==    by 0x509031: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0xa418020 is 1,312 bytes inside a block of size 2,968 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x5751C4: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12648==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x421334: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x57557C: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12648==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C2E68: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0xa416020 is 240 bytes inside a block of size 2,576 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B287B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C13C7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x545DEC: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x557788: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x508FA0: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Address 0xa41d020 is 608 bytes inside a block of size 813 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C2E68: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12648==    by 0x4DAA16: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12648==    by 0x5751C4: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12648==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0xa41e020 is 688 bytes inside a block of size 966 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x508FA0: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x421334: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x5089CC: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x509020: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0xa41e020 is 688 bytes inside a block of size 966 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x508FA0: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x421334: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12648==    by 0x5089CC: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==  Address 0xa70a020 is 54,832 bytes inside a block of size 57,308 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==  Address 0xa6dc020 is 864 bytes inside a block of size 1,008 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBFA: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==  Address 0xa6e5020 is 1,376 bytes inside a block of size 3,240 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12648==    by 0x520F48: PyUnicodeUCS4_Concat (in /usr/bin/python2.7)
==12648==    by 0x509006: PyString_Format (in /usr/bin/python2.7)
==12648==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Address 0x5db5020 is 16 bytes after an unallocated block of size 768 in arena "client"
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5ed7020 is 32 bytes before a block of size 384 in arena "client"
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5ed9020 is 352 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CF92A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5ed9020 is 352 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5f6c020 is 46,528 bytes inside a block of size 49,152 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A247E: PyDict_Merge (in /usr/bin/python2.7)
==12648==    by 0x511315: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x70a2020 is 176 bytes inside a block of size 1,076 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5f57020 is 368 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x7037020 is 0 bytes inside a block of size 280 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B344E: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x6ea8020 is 2,368 bytes inside a block of size 4,097 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A3F47: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A4119: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CF92A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x6d9f020 is 320 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x6d9f020 is 320 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x6e86020 is 32 bytes before an unallocated block of size 272 in arena "client"
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x6149020 is 256 bytes inside a block of size 1,104 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x516811: ??? (in /usr/bin/python2.7)
==12648==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12648==    by 0x557657: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5eea020 is 800 bytes inside a block of size 1,104 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x51718D: ??? (in /usr/bin/python2.7)
==12648==    by 0x577F29: ??? (in /usr/bin/python2.7)
==12648==    by 0x57738E: ??? (in /usr/bin/python2.7)
==12648==    by 0x557CCA: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CF92A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5dc4020 is 240 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12648==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCA6: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5f0f020 is 96 bytes inside a block of size 1,536 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC5BC: ??? (in /usr/bin/python2.7)
==12648==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12648==    by 0x4FBB5E: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A247E: PyDict_Merge (in /usr/bin/python2.7)
==12648==    by 0x421BD5: ??? (in /usr/bin/python2.7)
==12648==    by 0x51A8AB: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
==12648==    by 0x5B7B1A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4C30CD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0xbd58020 is 592 bytes inside a block of size 768 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DF254: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DF254: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x49B249: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DF254: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BA22B: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12648==    by 0x42C09D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BCE86: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FCCE9: _PyImport_Fini (in /usr/bin/python2.7)
==12648==    by 0x4F8E18: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x7090020 is 2,400 bytes inside a block of size 4,097 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4AA2E1: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4A9C82: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12648==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12648==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12648==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x49B249: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FED9D: PyInterpreterState_Clear (in /usr/bin/python2.7)
==12648==    by 0x4F8E20: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x603f020 is 720 bytes inside a block of size 1,105 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12648==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12648==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12648==    by 0x4B3100: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12648==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12648==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12648==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12648==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12648==    by 0x49B249: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FED9D: PyInterpreterState_Clear (in /usr/bin/python2.7)
==12648==    by 0x4F8E20: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x6080020 is 80 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFD9B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4DFD9B: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12648==    by 0x4F7591: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12648==    by 0x4FEDBB: PyInterpreterState_Clear (in /usr/bin/python2.7)
==12648==    by 0x4F8E20: Py_Finalize (in /usr/bin/python2.7)
==12648==  Address 0x6052020 is 240 bytes inside a block of size 552 free'd
==12648==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12648==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12648==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12648== 
==12648== Invalid read of size 4
==12648==    at 0x501F37: PyGrammar_RemoveAccelerators (in /usr/bin/python2.7)
==12648==    by 0x4F8E83: Py_Finalize (in /usr/bin/python2.7)
==12648==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12648==    by 0x507782F: (below main) (libc-start.c:291)
==12648==  Address 0x5fb2020 is 144 bytes inside a block of size 200 free'd
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x55793C: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648==  Block was alloc'd at
==12648==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12648==    by 0x495405: ??? (in /usr/bin/python2.7)
==12648==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12648==    by 0x55797E: ??? (in /usr/bin/python2.7)
==12648==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12648==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12648==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12648==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12648==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12648==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12648== 
==12648== 
==12648== HEAP SUMMARY:
==12648==     in use at exit: 2,847,527 bytes in 2,521 blocks
==12648==   total heap usage: 31,956 allocs, 29,435 frees, 28,901,690 bytes allocated
==12648== 
==12648== LEAK SUMMARY:
==12648==    definitely lost: 0 bytes in 0 blocks
==12648==    indirectly lost: 0 bytes in 0 blocks
==12648==      possibly lost: 5,520 bytes in 10 blocks
==12648==    still reachable: 2,842,007 bytes in 2,511 blocks
==12648==         suppressed: 0 bytes in 0 blocks
==12648== Rerun with --leak-check=full to see details of leaked memory
==12648== 
==12648== For counts of detected and suppressed errors, rerun with: -v
==12648== Use --track-origins=yes to see where uninitialised values come from
==12648== ERROR SUMMARY: 871 errors from 67 contexts (suppressed: 0 from 0)
