==12679== Memcheck, a memory error detector
==12679== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==12679== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==12679== Command: python2 issue.py
==12679== Parent PID: 5796
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBFA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0x5e02020 is 2,624 bytes inside a block of size 2,731 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==  Address 0x5e5a020 is 256 bytes inside a block of size 2,711 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x5e48020 is 96 bytes inside a block of size 1,008 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0x5df6020 is 10,224 bytes inside a block of size 11,374 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==  Address 0x5df9020 is 1,168 bytes inside a block of size 1,384 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3038: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B344E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFDA8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==  Address 0x5f5a020 is 4,448 bytes inside a block of size 4,784 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3038: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4B8D51: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12679==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0x5fb4020 is 592 bytes inside a block of size 676 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B94F1: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12679==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B9120: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12679==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4F7EB7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E281C: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x6012020 is 0 bytes inside a block of size 768 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBED6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x421334: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC138: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC15B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC0F5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC4AF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBEB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4F7E29: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E281C: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x4EB2E4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5421: PyRun_FileExFlags (in /usr/bin/python2.7)
==12679==    by 0x4E3CD5: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==12679==    by 0x493AE1: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x6099020 is 33,248 bytes inside a block of size 36,032 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B7072: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B4174: PyParser_ASTFromFile (in /usr/bin/python2.7)
==12679==    by 0x4E53EB: PyRun_FileExFlags (in /usr/bin/python2.7)
==12679==    by 0x4E3CD5: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==12679==    by 0x493AE1: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B4FFC: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B4174: PyParser_ASTFromFile (in /usr/bin/python2.7)
==12679==    by 0x4E53EB: PyRun_FileExFlags (in /usr/bin/python2.7)
==12679==    by 0x4E3CD5: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==12679==    by 0x493AE1: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0x6d3d020 is 320 bytes inside a block of size 552 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12679==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12679==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12679==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12679==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12679==    by 0x4BB77A: PyFrame_New (in /usr/bin/python2.7)
==12679==    by 0x4C12A8: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x6dcc020 is 32 bytes before a block of size 544 in arena "client"
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x6dcc020 is 32 bytes before a block of size 544 in arena "client"
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FFA5F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==12679==    by 0x4BAE2E: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x6dad020 is 224 bytes inside a block of size 257 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x514378: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF5D7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C138B: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50FB78: PyByteArray_Resize (in /usr/bin/python2.7)
==12679==    by 0x50F55B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4AA9AA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4E16A7: ??? (in /usr/bin/python2.7)
==12679==    by 0x519089: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==  Address 0x6eec020 is 35,392 bytes inside a block of size 36,032 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B7072: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B4FFC: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4F7E29: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF4E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x6ef4020 is 16 bytes after a block of size 32 in arena "client"
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4ECBCE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x6ef5020 is 0 bytes after a block of size 32 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5F26: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7D2C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5F26: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7D2C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4F7E02: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AFE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0x6ef5020 is 0 bytes after a block of size 32 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5F26: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7D2C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5F26: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7D2C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4BA22B: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==  Address 0x6edf020 is 416 bytes inside a block of size 2,095 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x5130BA: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x514123: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x5139DF: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==  Address 0x6ef9020 is 16 bytes before a block of size 56 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DAD3D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x49A3B0: ??? (in /usr/bin/python2.7)
==12679==    by 0x49A1CB: PySequence_List (in /usr/bin/python2.7)
==12679==    by 0x4DAC4A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x514123: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==  Address 0x6ef9020 is 16 bytes before a block of size 56 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49B264: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DAD3D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x49A3B0: ??? (in /usr/bin/python2.7)
==12679==    by 0x49A1CB: PySequence_List (in /usr/bin/python2.7)
==12679==    by 0x4DAC4A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x5130BA: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==  Address 0x6efa020 is 1,008 bytes inside a block of size 1,689 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x514123: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x5139DF: ??? (in /usr/bin/python2.7)
==12679==    by 0x512CA9: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C37EC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F87BD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFC1A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x6f27020 is 128 bytes inside a block of size 768 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E776B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12679==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E6E5B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12679==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EF828: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x6f29020 is 16 bytes after a block of size 32 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5F26: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7D2C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF34: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49539B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E5F26: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7D2C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF1A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F87A6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFC1A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF68: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x6f41020 is 224 bytes inside a block of size 768 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7781: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12679==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E6E37: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E7565: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E324C: PySymtable_Build (in /usr/bin/python2.7)
==12679==    by 0x4E27A4: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Conditional jump or move depends on uninitialised value(s)
==12679==    at 0x4B5B72: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Use of uninitialised value of size 8
==12679==    at 0x4B5B8A: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EE69B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC083: ??? (in /usr/bin/python2.7)
==12679==    by 0x4ECB80: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF83: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x6f7a020 is 720 bytes inside a block of size 768 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7F32: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7CA5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFBF7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF4E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679==    by 0x4E2B69: PyAST_Compile (in /usr/bin/python2.7)
==12679==    by 0x5190AD: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EDDF0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC06C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC387: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC19E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EC184: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EF7FB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EFADF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBF4E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F0AB4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EBE92: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x507C2F: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x72eb020 is 608 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x516811: ??? (in /usr/bin/python2.7)
==12679==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12679==    by 0x557657: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4B287B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C13C7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0x7417020 is 112 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x557898: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x516811: ??? (in /usr/bin/python2.7)
==12679==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12679==    by 0x557657: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C2E68: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0x7417020 is 112 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x557898: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x516811: ??? (in /usr/bin/python2.7)
==12679==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12679==    by 0x557657: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x83b7020 is 16 bytes inside a block of size 368 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3275: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4D20C7: PyMember_SetOne (in /usr/bin/python2.7)
==12679==    by 0x42C38B: ??? (in /usr/bin/python2.7)
==12679==    by 0x42C09D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BCE86: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0x876f020 is 368 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x516811: ??? (in /usr/bin/python2.7)
==12679==    by 0x551E95: ??? (in /usr/bin/python2.7)
==12679==    by 0x557657: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==  Address 0xa38b020 is 576 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x5579DC: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51718D: ??? (in /usr/bin/python2.7)
==12679==    by 0x577F29: ??? (in /usr/bin/python2.7)
==12679==    by 0x57738E: ??? (in /usr/bin/python2.7)
==12679==    by 0x557CCA: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545DEC: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==  Address 0xa38c020 is 736 bytes inside a block of size 804 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x421334: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B287B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C13C7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0xa38d020 is 2,272 bytes inside a block of size 3,204 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545DEC: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12679==    by 0x509031: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0xa38f020 is 64 bytes inside a block of size 2,968 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x5751C4: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12679==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x421334: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x57557C: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12679==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C2E68: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0xa38d020 is 2,272 bytes inside a block of size 3,204 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545DEC: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x545F7A: PyUnicodeUCS4_Join (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x557788: ??? (in /usr/bin/python2.7)
==12679==    by 0x55723A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x508FA0: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Address 0xa395020 is 608 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x514B2E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51718D: ??? (in /usr/bin/python2.7)
==12679==    by 0x577F29: ??? (in /usr/bin/python2.7)
==12679==    by 0x514AEB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x5751C4: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12679==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0xa395020 is 608 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x514B2E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51718D: ??? (in /usr/bin/python2.7)
==12679==    by 0x577F29: ??? (in /usr/bin/python2.7)
==12679==    by 0x514AEB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x509020: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0xa395020 is 608 bytes inside a block of size 1,104 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x514B2E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51718D: ??? (in /usr/bin/python2.7)
==12679==    by 0x577F29: ??? (in /usr/bin/python2.7)
==12679==    by 0x514AEB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x501E78: ??? (in /usr/bin/python2.7)
==12679==    by 0x520F48: PyUnicodeUCS4_Concat (in /usr/bin/python2.7)
==12679==    by 0x509006: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Address 0xa39d020 is 1,520 bytes inside a block of size 2,352 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x5751C4: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12679==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x421334: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x57557C: PyUnicodeUCS4_Format (in /usr/bin/python2.7)
==12679==    by 0x508FDC: PyString_Format (in /usr/bin/python2.7)
==12679==    by 0x4BDCAC: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Address 0xbaf3020 is 53,552 bytes inside a block of size 57,308 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2FA0: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B2F6B: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==  Address 0xbac5020 is 496 bytes inside a block of size 848 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B344E: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A93A6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBFA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==  Address 0xbace020 is 96 bytes inside a block of size 3,240 free'd
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x495405: ??? (in /usr/bin/python2.7)
==12679==    by 0x495044: PyList_Append (in /usr/bin/python2.7)
==12679==    by 0x4B3167: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3251: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3438: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679== 
==12679== Conditional jump or move depends on uninitialised value(s)
==12679==    at 0x419678: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x4212DA: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF32A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C9305: PyUnicodeUCS4_DecodeUTF8Stateful (in /usr/bin/python2.7)
==12679==    by 0x4B3726: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==  Address 0x5eb1020 is 544 bytes inside a block of size 552 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Conditional jump or move depends on uninitialised value(s)
==12679==    at 0x419678: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Use of uninitialised value of size 8
==12679==    at 0x41968C: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Conditional jump or move depends on uninitialised value(s)
==12679==    at 0x4212E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A904D: _PyString_Resize (in /usr/bin/python2.7)
==12679==    by 0x51A73D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x75CF38A: ??? (in /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Conditional jump or move depends on uninitialised value(s)
==12679==    at 0x419678: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x75CF429: ??? (in /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D55F2: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x75CF429: ??? (in /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so)
==12679==    by 0x4C17AB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D55F2: ??? (in /usr/bin/python2.7)
==12679==  Address 0x60cb020 is 144 bytes inside a block of size 552 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12679==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5ed8020 is 0 bytes inside a block of size 552 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5ed9020 is 192 bytes inside a block of size 576 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x418668: _PyObject_GC_Malloc (in /usr/bin/python2.7)
==12679==    by 0x4BA6A2: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CF92A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5ed9020 is 192 bytes inside a block of size 576 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CFBD7: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2B21: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x418668: _PyObject_GC_Malloc (in /usr/bin/python2.7)
==12679==    by 0x4BA6A2: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A7FD4: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A3F37: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5f6c020 is 46,528 bytes inside a block of size 49,152 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A9674: ??? (in /usr/bin/python2.7)
==12679==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12679==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Block was alloc'd at
==12679==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x498DDC: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A247E: PyDict_Merge (in /usr/bin/python2.7)
==12679==    by 0x511315: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x7216020 is 4,048 bytes inside a block of size 4,096 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50D254A: _IO_setb (genops.c:382)
==12679==    by 0x50D08ED: _IO_file_close_it@@GLIBC_2.2.5 (fileops.c:185)
==12679==    by 0x50C43EE: fclose@@GLIBC_2.2.5 (iofclose.c:58)
==12679==    by 0x4B2AC6: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C41D4: _IO_file_doallocate (filedoalloc.c:127)
==12679==    by 0x50D2593: _IO_doallocbuf (genops.c:398)
==12679==    by 0x50D169B: _IO_file_underflow@@GLIBC_2.2.5 (fileops.c:556)
==12679==    by 0x50D260D: _IO_default_uflow (genops.c:413)
==12679==    by 0x50CD107: getc (getc.c:38)
==12679==    by 0x4B2E5F: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2D9A: PyMarshal_ReadLongFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2A84: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5f57020 is 2,416 bytes inside a block of size 4,097 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51A0FD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51A038: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12679==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x6ea7020 is 2,272 bytes inside a block of size 4,097 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A4020: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A4119: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679== 
==12679== Conditional jump or move depends on uninitialised value(s)
==12679==    at 0x419678: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679== 
==12679== Use of uninitialised value of size 8
==12679==    at 0x41968C: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x495DDA: PyDict_SetItem (in /usr/bin/python2.7)
==12679==    by 0x4FC2E8: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x6148020 is 288 bytes inside a block of size 552 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5eea020 is 3,808 bytes inside a block of size 4,097 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A4020: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A4119: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CF92A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x6ea8020 is 512 bytes inside a block of size 869 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12679==    by 0x4B3100: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B340C: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B32FF: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x6d9e020 is 208 bytes inside a block of size 552 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4EB30E: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5f0c020 is 208 bytes inside a block of size 552 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4D5C: __fopen_internal (iofopen.c:90)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50C4CDC: __fopen_internal (iofopen.c:69)
==12679==    by 0x4A9E97: ??? (in /usr/bin/python2.7)
==12679==    by 0x51A075: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBC2D: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0xbc46020 is 3,408 bytes inside a block of size 4,097 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A4020: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A4119: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FCCE9: _PyImport_Fini (in /usr/bin/python2.7)
==12679==    by 0x4F8E18: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x71f3020 is 3,792 bytes inside a block of size 4,097 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4AA2E1: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4A9C82: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4ABD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A45DC: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679==    by 0x4A59E3: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4C5E0F: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==12679==    by 0x4BE6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==    by 0x4B96DE: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==12679==    by 0x4B2B05: ??? (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFBB5: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x49B249: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FED9D: PyInterpreterState_Clear (in /usr/bin/python2.7)
==12679==    by 0x4F8E20: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x603f020 is 720 bytes inside a block of size 1,105 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4FC339: _PyModule_Clear (in /usr/bin/python2.7)
==12679==    by 0x4FBB4C: PyImport_Cleanup (in /usr/bin/python2.7)
==12679==    by 0x4F8E13: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x49FF81: PyString_FromStringAndSize (in /usr/bin/python2.7)
==12679==    by 0x4B3100: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B322D: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3422: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B3015: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==12679==    by 0x4B2F95: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==12679==    by 0x4B2EDD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B2ABB: ??? (in /usr/bin/python2.7)
==12679==    by 0x4B402B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A4AE0: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A42C8: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CFCDE: ??? (in /usr/bin/python2.7)
==12679==    by 0x4CF99B: ??? (in /usr/bin/python2.7)
==12679==    by 0x49B249: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FED9D: PyInterpreterState_Clear (in /usr/bin/python2.7)
==12679==    by 0x4F8E20: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x6080020 is 4,064 bytes inside a block of size 4,097 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51A0FD: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x51A038: ??? (in /usr/bin/python2.7)
==12679==    by 0x4BC3F9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4D54B8: ??? (in /usr/bin/python2.7)
==12679==    by 0x4EEBED: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A577D: PyObject_Call (in /usr/bin/python2.7)
==12679==    by 0x4D8F91: PyInstance_New (in /usr/bin/python2.7)
==12679==    by 0x4C15BE: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4B97A5: PyEval_EvalCode (in /usr/bin/python2.7)
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x41966F: PyObject_Free (in /usr/bin/python2.7)
==12679==    by 0x4CF92A: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DFDB1: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4DFD9B: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A9373: ??? (in /usr/bin/python2.7)
==12679==    by 0x4F7591: ??? (in /usr/bin/python2.7)
==12679==    by 0x4A94E2: ??? (in /usr/bin/python2.7)
==12679==    by 0x4FEDBB: PyInterpreterState_Clear (in /usr/bin/python2.7)
==12679==    by 0x4F8E20: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==  Address 0x6053020 is 32 bytes before a block of size 592 in arena "client"
==12679== 
==12679== Invalid read of size 4
==12679==    at 0x501F37: PyGrammar_RemoveAccelerators (in /usr/bin/python2.7)
==12679==    by 0x4F8E83: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Address 0x5fb3020 is 128 bytes inside a block of size 668 free'd
==12679==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x50213F: PyGrammar_RemoveAccelerators (in /usr/bin/python2.7)
==12679==    by 0x4F8E83: Py_Finalize (in /usr/bin/python2.7)
==12679==    by 0x4938EB: Py_Main (in /usr/bin/python2.7)
==12679==    by 0x507782F: (below main) (libc-start.c:291)
==12679==  Block was alloc'd at
==12679==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12679==    by 0x4B9172: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==12679==    by 0x4B849A: ??? (in /usr/bin/python2.7)
==12679==    by 0x519038: PyRun_StringFlags (in /usr/bin/python2.7)
==12679==    by 0x4C3C77: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C1E6E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679==    by 0x4C16E6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4C136E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==12679==    by 0x4B9AB5: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==12679== 
==12679== 
==12679== HEAP SUMMARY:
==12679==     in use at exit: 2,881,558 bytes in 2,544 blocks
==12679==   total heap usage: 32,950 allocs, 30,406 frees, 29,552,447 bytes allocated
==12679== 
==12679== LEAK SUMMARY:
==12679==    definitely lost: 0 bytes in 0 blocks
==12679==    indirectly lost: 0 bytes in 0 blocks
==12679==      possibly lost: 6,056 bytes in 11 blocks
==12679==    still reachable: 2,875,502 bytes in 2,533 blocks
==12679==         suppressed: 0 bytes in 0 blocks
==12679== Rerun with --leak-check=full to see details of leaked memory
==12679== 
==12679== For counts of detected and suppressed errors, rerun with: -v
==12679== Use --track-origins=yes to see where uninitialised values come from
==12679== ERROR SUMMARY: 880 errors from 71 contexts (suppressed: 0 from 0)
